### ISSUE TITLE
Question: use with react-formal or yup

### ISSUE THREAD

**Issue by rosskevin** [seanhess/runtime-types#9]
I'm interested to use flowtype definitions with https://github.com/jquense/react-formal

I've prototyped a simple form with [yup](https://github.com/jquense/yup), and it looks quite similar to a flowtype definition.

Any thoughts on:
1. integrating this with react-forma?l; or
2. integrating this with yup?

I like the idea of using the flowtypes as the one and only definition.

**Comment by seanhess** [comment]
It should be fairly easy for you to convert the runtime schema description provided by this library into the format needed for react-formal or yup. Per the main page:

```
var types = require('runtime-types')
var path  = require('path')

// read the file into a runtime type description
var MyTypes = types.readFile(path.join(__dirname, '../test/example-types.js'))

// MyTypes is now equal to:
{
  PhoneNumber: { name: 'string' },

  User: {
    name: 'Object',
    properties: [
      { key: 'username', type: { name: 'string' } },
      { key: 'age',      type: { name: 'number' } },
      { key: 'phone',    type: { name: 'PhoneNumber' } },
      { key: 'created',  type: { name: 'Date', nullable: true } } 
    ]
  }
}
```

So you can convert that into yup's by writing functions that walk through each object and return a schema. Here's some functions to start:

```
function propertyToYup(property) {
   if (property.type.name == "string") {
      return yup.string()
   }
   else ...
}

function schemaToYup(objectSchema) {
   return ?? // should return the same thing as yup.object.shape({})
   // just map through the properties.
}
```

It'll take some work but it's doable. I don't write much JS any more (I've been doing a lot of Elm and Haskell instead), so I probably won't write the integration, but it should be fairly straightforward. Let me know if you get stuck!

**Comment by rosskevin** [comment]
Thanks!  I'll consider this as I try to wire together my optimal framework.
